In [1]:
import pandas as pd
import numpy as np
import nltk
from nltk.corpus import stopwords
import pickle


In [2]:
#Text cleaning

# 1. Remove special character
# 2. Lower case
# 3. stop words
# 4. stemming


In [3]:
df=pd.read_csv("SET2_dataSet_final12.csv",encoding="iso-8859-1")
df.shape

(1600, 2)

In [4]:

df.head()

Title Category
0  Madagascar Street Food!!! Super RARE Malagasy ...     Food
1            42 Foods You Need To Eat Before You Die     Food
2              Gordon Ramsay’s Top 5 Indian Dishes     Food
3         To Use Chopsticks - In About A Minute 🍜     Food
4                       Trying Indian Food 1st Time!     Food

In [5]:
#convert title into lowercase

def convert_lowercase(f_text):
    return f_text.lower()

In [6]:
df.shape

(1600, 2)

In [7]:
df.head(3)

Title Category
0  Madagascar Street Food!!! Super RARE Malagasy ...     Food
1            42 Foods You Need To Eat Before You Die     Food
2              Gordon Ramsay’s Top 5 Indian Dishes     Food

In [8]:
#Removing special character

def remove_special(title):
    f_text=''
    for i in title.split(' '): 
        for j in i:
            if j.isalpha():
               f_text=f_text+j 
        f_text=f_text+' '
    return f_text

In [9]:
remove_special = remove_special
pickle.dump(remove_special,open("remove_special.pkl",'wb'))


In [10]:
df.head(5)

Title Category
0  Madagascar Street Food!!! Super RARE Malagasy ...     Food
1            42 Foods You Need To Eat Before You Die     Food
2              Gordon Ramsay’s Top 5 Indian Dishes     Food
3         To Use Chopsticks - In About A Minute 🍜     Food
4                       Trying Indian Food 1st Time!     Food

In [11]:
df['Title']=df['Title'].apply(remove_special)


In [12]:
df['Category'].replace({'computer science':0, 'Food':1, 'Art&Music':2,'other':3 },inplace=True)


In [13]:
df.head(8)

Title  Category
0  Madagascar Street Food Super RARE Malagasy Vil...         1
1              Foods You Need To Eat Before You Die          1
2                Gordon Ramsayâs Top  Indian Dishes          1
3            To Use Chopsticks  In About A Minute ð          1
4                        Trying Indian Food st Time          1
5  Blippi Tours the Chocolate Factory  Learn abou...         1
6    EGYPT Vegetarian food  Mobile Sim  Indian Spy           1
7    Chinese Street Food Liuhe Tourist Night Market          1

In [14]:
df.tail(8)

Title  Category
1592  The Best Winter Sports Destinations Skiing Sno...         3
1593  The Best Wildlife Destinations A Journey Throu...         3
1594  The Best Beaches for Surfing Riding the Waves ...         3
1595  Exploring the Best Spa Destinations Relaxation...         3
1596  The Best Camping Destinations Sleeping Under t...         3
1597  A Journey Through Latin America Discovering th...         3
1598  The Best Destinations for Road Cycling Riding ...         3
1599  The Best Destinations for Food and Wine Lovers...         3

In [15]:
def remove_stopWords(f_text):
    stop_w = set(stopwords.words('english'))
    x=[]
    for i in f_text.split():
        if i not in stop_w:
            x.append(i)
    f_sentance=x[:]
    x.clear()
    return f_sentance

In [16]:
remove_stopWords = remove_stopWords
pickle.dump(remove_stopWords,open("remove_stopWords.pkl",'wb'))

In [17]:
df['Title']=df['Title'].apply(remove_stopWords)
df.head(3)

Title  Category
0  [Madagascar, Street, Food, Super, RARE, Malaga...         1
1      [Foods, You, Need, To, Eat, Before, You, Die]         1
2            [Gordon, Ramsayâs, Top, Indian, Dishes]         1

In [18]:
#Word stemming
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

def stem_word(text):
    y=[]
    for i in text:
        y.append(ps.stem(i))
    z=y[:]
    y.clear()
    return z

In [19]:
stem_word = stem_word
pickle.dump(stem_word,open("stem_word.pkl",'wb'))

In [20]:
df['Title']=df['Title'].apply(stem_word)
df.tail(3)

Title  Category
1597  [a, journey, through, latin, america, discov, ...         3
1598  [the, best, destin, road, cycl, ride, through,...         3
1599  [the, best, destin, food, wine, lover, a, jour...         3

In [21]:
#join list to make string

def join_back(list_input):
    return " ".join(list_input)


In [22]:
df['Title']=df['Title'].apply(join_back)


In [23]:
df['Title']=df['Title'].apply(convert_lowercase)

In [24]:
df.loc[0:3,'Title']

0    madagascar street food super rare malagasi vil...
1                   food you need to eat befor you die
2                       gordon ramsayâ top indian dish
3                  to use chopstick in about a minut ð
Name: Title, dtype: object

In [25]:
x=df.iloc[:,0:1].values

In [26]:
x[0:3]


array([['madagascar street food super rare malagasi villag food'],
       ['food you need to eat befor you die'],
       ['gordon ramsayâ top indian dish']], dtype=object)

In [27]:
y=df.iloc[:,-1].values
y.shape

(1600,)

In [28]:
y  #why used

array([1, 1, 1, ..., 3, 3, 3], dtype=int64)

In [29]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=3200)
#extract new word and store in v_obj with index by fit()
#Encode the Document using transform

x=cv.fit_transform(df['Title']).toarray()
x.shape


(1600, 3200)

In [30]:
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [31]:
df = pd.DataFrame(data=x, columns=cv.get_feature_names_out())

In [32]:
keywords= cv.get_feature_names_out()

In [33]:
keywords.shape

(3200,)

In [34]:
#Train an test data set split

In [35]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test =train_test_split(x,y,test_size=0.2)

In [36]:
X_train.shape

(1280, 3200)

In [37]:
X_test.shape

(320, 3200)

In [38]:
y_train.shape

(1280,)

In [39]:

X_train.max()

5

In [40]:
#Feature scalling
# X_train= X_train/3
# X_test= X_test/3

In [41]:
X_train[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [42]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense,Flatten

In [43]:
X_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [44]:
#creating model

from keras.models import Sequential
model= Sequential()

model.add( Dense(128, input_dim=3200, activation='sigmoid'))
model.add( Dense(4,activation='softmax'))

In [45]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 128)               409728    
                                                                 
 dense_1 (Dense)             (None, 4)                 516       
                                                                 
Total params: 410,244
Trainable params: 410,244
Non-trainable params: 0
_________________________________________________________________


In [46]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy')

In [47]:
# import tensorflow as tf

# X_train_tensor = tf.convert_to_tensor(X_train, dtype=tf.float32)
# y_train_tensor = tf.convert_to_tensor(y_train, dtype=tf.int32)

In [48]:
model.fit(X_train, y_train, epochs=6, validation_split=0.2)

Epoch 1/6
32/32 [==============================] - 1s 13ms/step - loss: 1.3068 - val_loss: 1.2249
Epoch 2/6
32/32 [==============================] - 0s 8ms/step - loss: 1.0988 - val_loss: 1.0644
Epoch 3/6
32/32 [==============================] - 0s 8ms/step - loss: 0.9268 - val_loss: 0.9264
Epoch 4/6
32/32 [==============================] - 0s 8ms/step - loss: 0.7663 - val_loss: 0.7983
Epoch 5/6
32/32 [==============================] - 0s 9ms/step - loss: 0.6241 - val_loss: 0.6926
Epoch 6/6
32/32 [==============================] - 0s 9ms/step - loss: 0.5046 - val_loss: 0.5934


In [49]:
# probablity of each row with class label
y_prob = model.predict(X_test)

10/10 [==============================] - 0s 3ms/step


In [50]:
y_prob[1:5]

array([[0.15207629, 0.20226115, 0.45012495, 0.19553763],
       [0.06217979, 0.06612729, 0.14189194, 0.72980094],
       [0.15247598, 0.16767019, 0.17847657, 0.5013772 ],
       [0.62647086, 0.10352749, 0.10316074, 0.16684085]], dtype=float32)

In [51]:

y_pred= y_prob.argmax(axis =1)

In [52]:
y_pred

array([1, 2, 3, 3, 0, 0, 3, 2, 2, 0, 0, 1, 1, 3, 0, 0, 3, 1, 0, 1, 3, 0,
       0, 2, 0, 0, 0, 2, 1, 2, 0, 2, 1, 1, 0, 2, 3, 1, 3, 3, 3, 2, 1, 3,
       0, 2, 3, 0, 2, 2, 2, 1, 2, 3, 2, 0, 3, 0, 2, 2, 2, 2, 2, 1, 1, 3,
       0, 1, 0, 2, 1, 3, 2, 0, 1, 3, 2, 2, 0, 2, 2, 3, 2, 0, 3, 3, 1, 2,
       1, 3, 2, 2, 3, 1, 1, 2, 0, 2, 3, 2, 3, 2, 2, 3, 1, 0, 1, 0, 0, 2,
       0, 2, 3, 2, 3, 3, 3, 1, 1, 2, 2, 0, 3, 0, 1, 2, 1, 3, 3, 1, 0, 1,
       3, 0, 0, 1, 0, 0, 3, 1, 0, 2, 0, 2, 3, 3, 0, 1, 2, 3, 3, 0, 3, 3,
       0, 0, 3, 3, 0, 2, 2, 0, 1, 2, 2, 3, 2, 3, 0, 2, 3, 2, 2, 1, 3, 2,
       2, 1, 2, 2, 0, 2, 1, 2, 3, 2, 1, 0, 0, 2, 0, 1, 0, 2, 0, 0, 1, 1,
       2, 2, 2, 2, 1, 1, 2, 1, 1, 1, 1, 0, 3, 0, 3, 1, 1, 3, 2, 1, 2, 2,
       2, 0, 1, 3, 1, 3, 2, 3, 0, 2, 3, 3, 3, 0, 0, 2, 2, 2, 1, 1, 2, 2,
       2, 2, 2, 1, 2, 2, 1, 0, 3, 2, 0, 2, 0, 1, 3, 0, 0, 0, 2, 2, 0, 2,
       3, 0, 2, 0, 3, 2, 2, 3, 2, 2, 2, 3, 3, 2, 3, 2, 3, 0, 0, 2, 0, 2,
       0, 2, 1, 1, 1, 2, 3, 0, 2, 0, 3, 0, 0, 1, 3,

In [53]:
# calculate accuracy

from sklearn.metrics import accuracy_score
accuracy_score( y_test, y_pred)

0.8875

In [54]:
X_test[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [55]:
y_pred

array([1, 2, 3, 3, 0, 0, 3, 2, 2, 0, 0, 1, 1, 3, 0, 0, 3, 1, 0, 1, 3, 0,
       0, 2, 0, 0, 0, 2, 1, 2, 0, 2, 1, 1, 0, 2, 3, 1, 3, 3, 3, 2, 1, 3,
       0, 2, 3, 0, 2, 2, 2, 1, 2, 3, 2, 0, 3, 0, 2, 2, 2, 2, 2, 1, 1, 3,
       0, 1, 0, 2, 1, 3, 2, 0, 1, 3, 2, 2, 0, 2, 2, 3, 2, 0, 3, 3, 1, 2,
       1, 3, 2, 2, 3, 1, 1, 2, 0, 2, 3, 2, 3, 2, 2, 3, 1, 0, 1, 0, 0, 2,
       0, 2, 3, 2, 3, 3, 3, 1, 1, 2, 2, 0, 3, 0, 1, 2, 1, 3, 3, 1, 0, 1,
       3, 0, 0, 1, 0, 0, 3, 1, 0, 2, 0, 2, 3, 3, 0, 1, 2, 3, 3, 0, 3, 3,
       0, 0, 3, 3, 0, 2, 2, 0, 1, 2, 2, 3, 2, 3, 0, 2, 3, 2, 2, 1, 3, 2,
       2, 1, 2, 2, 0, 2, 1, 2, 3, 2, 1, 0, 0, 2, 0, 1, 0, 2, 0, 0, 1, 1,
       2, 2, 2, 2, 1, 1, 2, 1, 1, 1, 1, 0, 3, 0, 3, 1, 1, 3, 2, 1, 2, 2,
       2, 0, 1, 3, 1, 3, 2, 3, 0, 2, 3, 3, 3, 0, 0, 2, 2, 2, 1, 1, 2, 2,
       2, 2, 2, 1, 2, 2, 1, 0, 3, 2, 0, 2, 0, 1, 3, 0, 0, 0, 2, 2, 0, 2,
       3, 0, 2, 0, 3, 2, 2, 3, 2, 2, 2, 3, 3, 2, 3, 2, 3, 0, 0, 2, 0, 2,
       0, 2, 1, 1, 1, 2, 3, 0, 2, 0, 3, 0, 0, 1, 3,

In [56]:
y_test

array([1, 2, 3, 3, 0, 0, 3, 2, 2, 0, 0, 1, 1, 3, 0, 0, 3, 3, 0, 1, 3, 0,
       0, 2, 0, 0, 3, 2, 1, 2, 0, 3, 1, 1, 0, 2, 3, 1, 0, 0, 3, 2, 1, 3,
       0, 2, 3, 0, 2, 2, 2, 1, 2, 3, 2, 0, 3, 0, 2, 2, 3, 2, 3, 1, 1, 3,
       0, 1, 0, 2, 1, 3, 2, 0, 3, 0, 1, 2, 0, 2, 2, 3, 2, 0, 3, 3, 1, 2,
       1, 3, 2, 2, 3, 1, 1, 2, 0, 2, 3, 2, 3, 3, 2, 3, 1, 0, 1, 0, 0, 2,
       0, 2, 3, 1, 3, 3, 3, 1, 1, 2, 2, 0, 3, 0, 1, 2, 1, 3, 3, 1, 0, 1,
       3, 0, 0, 1, 0, 3, 3, 1, 0, 3, 0, 3, 0, 0, 0, 1, 2, 0, 3, 0, 3, 3,
       0, 0, 3, 3, 0, 2, 2, 0, 1, 2, 2, 3, 3, 3, 0, 2, 3, 2, 2, 1, 3, 3,
       2, 1, 2, 2, 0, 2, 1, 2, 3, 2, 1, 0, 0, 2, 0, 1, 0, 3, 0, 0, 1, 1,
       2, 2, 2, 3, 1, 1, 2, 1, 1, 1, 1, 0, 3, 0, 0, 1, 1, 3, 3, 1, 2, 2,
       2, 0, 1, 0, 1, 3, 2, 3, 0, 2, 0, 3, 0, 0, 0, 2, 2, 2, 1, 3, 2, 2,
       2, 2, 2, 1, 2, 2, 1, 0, 3, 2, 3, 2, 0, 1, 3, 0, 0, 0, 2, 2, 0, 2,
       3, 0, 2, 0, 3, 2, 2, 3, 0, 2, 2, 3, 3, 2, 3, 2, 3, 0, 0, 2, 0, 3,
       0, 2, 1, 1, 1, 2, 3, 3, 2, 0, 3, 3, 0, 1, 2,

In [57]:
x= model.predict(X_test[2].reshape(1,3200)).argmax(axis =1)

1/1 [==============================] - 0s 61ms/step


In [58]:
x

array([3], dtype=int64)

In [59]:
X_test[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [60]:
pickle.dump(model,open("set2_model.pkl",'wb'))

In [61]:
pickle.dump(X_test,open("set2_test_data.pkl",'wb'))

In [62]:
pickle.dump(keywords,open("keyword.pkl",'wb'))

In [63]:
remove_special1 = pickle.load(open('D:/Flask/SET2/remove_special.pkl', 'rb'))


In [64]:
title= remove_special1("Jack Ma's life-changing advice for young people")

In [65]:
title

'Jack Mas lifechanging advice for young people '